import React from 'react';
import { Monitor, Globe, ShieldCheck, Play, ArrowRight } from 'lucide-react';
import { Card } from './ui-elements';

export function BrowserView() {
  return (
    <Card className="h-full flex flex-col relative overflow-hidden">
      {/* Fake Browser Chrome */}
      <div className="h-12 bg-[#1a1a24] border-b border-white/10 flex items-center px-4 gap-4 z-20">
        <div className="flex gap-2">
          <div className="w-3 h-3 rounded-full bg-destructive/80" />
          <div className="w-3 h-3 rounded-full bg-amber-500/80" />
          <div className="w-3 h-3 rounded-full bg-emerald-500/80" />
        </div>
        
        <div className="flex items-center gap-2 text-muted-foreground">
          <ArrowRight size={14} className="opacity-50" />
        </div>

        <div className="flex-1 bg-black/50 border border-white/5 rounded-md h-7 flex items-center px-3 gap-2">
          <ShieldCheck size={12} className="text-emerald-400" />
          <span className="text-xs font-mono text-muted-foreground/70 truncate flex-1 select-none">
            playwright://agent-viewport
          </span>
          <Globe size={12} className="text-primary opacity-50" />
        </div>
      </div>

      {/* Viewport Area */}
      <div className="flex-1 relative flex items-center justify-center bg-black">
        {/* Background Grid Pattern generated by AI */}
        <img 
          src={`${import.meta.env.BASE_URL}images/cortex-bg.png`} 
          alt="Cyberpunk Grid" 
          className="absolute inset-0 w-full h-full object-cover opacity-30 mix-blend-screen"
        />
        
        <div className="relative z-10 flex flex-col items-center p-8 bg-black/60 backdrop-blur-md rounded-2xl neon-border">
          <div className="relative mb-6">
            <div className="absolute inset-0 rounded-full animate-ping bg-primary/20 blur-xl" />
            <div className="w-20 h-20 rounded-full border border-primary/50 bg-primary/10 flex items-center justify-center shadow-[0_0_30px_rgba(0,243,255,0.3)]">
              <Monitor size={32} className="text-primary" />
            </div>
            <div className="absolute -bottom-2 -right-2 w-8 h-8 rounded-full bg-secondary border border-black flex items-center justify-center">
              <Play size={14} className="text-white ml-0.5" />
            </div>
          </div>
          
          <h2 className="text-2xl font-display font-bold text-white tracking-wide mb-2">
            BROWSER <span className="text-primary neon-text">IDLE</span>
          </h2>
          <p className="text-muted-foreground text-sm max-w-sm text-center">
            The Playwright automation agent is currently standing by. Submit a browser task to initiate live telemetry.
          </p>
          
          <div className="mt-8 flex gap-3 opacity-60">
            <span className="px-3 py-1 rounded-full bg-white/5 text-[10px] font-mono border border-white/10 uppercase tracking-widest text-primary">Stealth Active</span>
            <span className="px-3 py-1 rounded-full bg-white/5 text-[10px] font-mono border border-white/10 uppercase tracking-widest text-emerald-400">Proxies Ready</span>
          </div>
        </div>
      </div>
    </Card>
  );
}
